[package]
name = "wgpu-burn-global-device"
authors.workspace = true
description = "Small library to establish a global wgpu device for use with burn"
edition.workspace = true
publish = true
license.workspace = true
rust-version.workspace = true
version.workspace = true
readme = "README.md"
documentation = "https://docs.rs/wgpu-burn-global-device"
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#local to package


#workspace internal gloss
# gloss-utils.workspace=true
# gloss-img.workspace=true
# gloss-burn-multibackend.workspace=true

#workspace third-party
cubecl.workspace=true
wgpu.workspace=true
once_cell.workspace=true
burn.workspace=true
burn-cubecl.workspace=true


[lints]
workspace = true



