[package]
name = "gloss-rs"
authors.workspace = true
description = "Top level crate for gloss-rs"
edition.workspace = true
publish = true
license.workspace = true
readme.workspace = true
rust-version.workspace = true
documentation = "https://docs.rs/gloss-rs"
repository.workspace = true
version.workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
easy-wgpu.workspace = true
gloss-img.workspace = true
gloss-renderer.workspace = true
gloss-utils.workspace = true
gloss-geometry.workspace = true

[lib]
crate-type = ["rlib"]

[lints]
workspace = true