[package]
name = "gloss-renderer"
authors.workspace = true
description = "Core renderer for gloss"
edition.workspace = true
publish = true
license.workspace = true
readme = "README.md"
rust-version.workspace = true
version.workspace = true
documentation = "https://docs.rs/gloss-renderer"
repository.workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lib]
crate-type = ["rlib"]

[features]
default = ["with-gui", "selector"]
# with-gui=["dep:egui", "dep:egui-winit", "dep:egui-wgpu", "dep:transform-gizmo", "easy-wgpu/with-gui"]
with-gui=["dep:egui", "dep:egui-winit", "dep:egui-wgpu", "easy-wgpu/with-gui"]
selector=[]
burn-torch = ["burn/tch", "easy-wgpu/burn-torch", "tch", "wgpu-cuda-interop/cuda"]

[dependencies]
# workspace internal gloss
easy-wgpu.workspace=true
gloss-utils.workspace=true
gloss-img.workspace=true
gloss-hecs.workspace=true
gloss-geometry.workspace=true
wgpu-burn-global-device.workspace=true
wgpu-cuda-interop= { workspace = true, optional = true }

# workspace third-party
cfg-if.workspace=true
bytemuck.workspace=true
env_logger.workspace=true
log.workspace=true
pollster.workspace=true
burn.workspace=true
cubecl.workspace=true
winit.workspace=true
wgpu.workspace=true
wgpu-hal.workspace=true
nalgebra.workspace=true
nalgebra-glm.workspace=true
image.workspace=true
tobj.workspace=true
once_cell.workspace=true
futures-lite.workspace=true
futures.workspace=true
gltf.workspace=true

# gui stuff
egui = { workspace = true, optional = true }
epaint={ workspace = true, optional = true }
egui-winit = { workspace = true, optional = true }
egui-wgpu = { workspace = true, optional = true }
# egui-gizmo = { workspace = true, optional = true }
# transform-gizmo = { workspace = true, optional = true }

enum-map.workspace=true
encase.workspace=true
wasm-timer.workspace=true
include-wgsl-oil.workspace=true
ktx2.workspace=true
config.workspace=true
serde.workspace=true
toml.workspace=true
smallvec.workspace=true
ply-rs.workspace=true
static_assertions.workspace=true
itertools.workspace=true
re_memory.workspace=true
strum_macros.workspace=true
crossbeam-channel.workspace=true
# pyo3-tch = { workspace = true, optional = true }
tch = { workspace=true, optional=true }


[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
abi_stable.workspace=true

# more dependancies for wasm https://sotrh.github.io/learn-wgpu/beginner/tutorial1-window/#added-support-for-the-web
[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook.workspace=true
console_log.workspace=true
wasm-bindgen.workspace=true
wasm-bindgen-futures.workspace=true
web-sys.workspace=true
js-sys.workspace=true

[target.x86_64-unknown-linux-gnu] #slightly faster linking
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[lints]
workspace = true
