[package]
name = "gloss-geometry"
authors.workspace = true
description = "Small library for geometry based utility functions in gloss"
edition.workspace = true
publish = true
license.workspace = true
rust-version.workspace = true
version.workspace = true
readme = "README.md"
documentation = "https://docs.rs/gloss-utils"
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#local to package


#workspace internal gloss
gloss-utils.workspace=true
gloss-img.workspace=true
gloss-burn-multibackend.workspace=true

#workspace third-party
log.workspace=true
nalgebra.workspace=true
wgpu.workspace=true
burn.workspace=true
burn-cubecl.workspace=true
cubecl.workspace=true
obj-exporter.workspace=true
ply-rs.workspace=true
image.workspace=true
itertools.workspace=true
strum.workspace=true
strum_macros.workspace=true



[lints]
workspace = true



